version: '3.3'

services:
  incluitec:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "incluitec"
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres


  postgres:
    build:
      context: ./DB
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5555
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=incluitec
    restart: unless-stopped

volumes:
  postgres-data: